#!/usr/bin/env python3
"""
gifzittofetch.py

Animated ASCII fetch tool with system specs + theme detection.
Reads frames generated by gif2ascii_clean.py.
"""

import os
import time
import shutil
import subprocess
from pathlib import Path


# ---------------------------------------------------------------------------
#  THEME DETECTION
# ---------------------------------------------------------------------------

def detect_theme():
    """
    Detect light or dark terminal background.
    Uses COLORTERM, terminal background RGB, and heuristic ANSI query.
    """
    # If user exports THEME=dark/light — respect that
    env = os.environ.get("THEME", "").lower()
    if env in ("dark", "light"):
        return env

    # Kitty & foot provide background color env
    bg = os.environ.get("KITTY_WINDOW_BACKGROUND")
    if bg:
        # Example: "rgb:1212/1212/1212"
        try:
            parts = bg.replace("rgb:", "").split("/")
            r = int(parts[0], 16)
            g = int(parts[1], 16)
            b = int(parts[2], 16)
            brightness = (r + g + b) / 3
            return "light" if brightness > 128 else "dark"
        except:
            pass

    # Heuristic: default to dark (most terminals)
    return "dark"


# ---------------------------------------------------------------------------
#  ASCII FRAME LOADING
# ---------------------------------------------------------------------------

def load_frames(folder: str):
    folder = Path(folder).expanduser()
    if not folder.exists():
        raise FileNotFoundError(f"Frame folder does not exist: {folder}")

    frames = sorted(folder.glob("frame_*.txt"))
    if not frames:
        raise FileNotFoundError(f"No frames found in {folder}")

    out = []
    for f in frames:
        with open(f, "r", encoding="utf-8") as fh:
            out.append(fh.read().splitlines())
    return out


# ---------------------------------------------------------------------------
#  SYSTEM INFO GATHERING (cross-platform, fast)
# ---------------------------------------------------------------------------

def run(cmd):
    try:
        return subprocess.check_output(cmd, shell=True, stderr=subprocess.DEVNULL).decode().strip()
    except:
        return "N/A"

def get_specs():
    specs = {}

    specs["os"] = run("uname -o")
    specs["kernel"] = run("uname -r")
    specs["host"] = run("hostname")
    specs["uptime"] = run("uptime -p").replace("up ", "")
    specs["shell"] = os.environ.get("SHELL", "N/A")

    specs["de"] = (
        os.environ.get("XDG_CURRENT_DESKTOP") or
        os.environ.get("DESKTOP_SESSION") or
        "N/A"
    )

    specs["wm"] = run("wmctrl -m | grep Name | awk '{print $2}'")

    specs["term"] = os.environ.get("TERM", "unknown")
    specs["terminal"] = run("ps -o comm= -p $(ps -o ppid= -p $$)") or specs["term"]

    specs["cpu"] = run("grep 'model name' /proc/cpuinfo | head -n1 | cut -d: -f2").strip()
    specs["gpu"] = (
        run("lspci | grep -i 'vga\|3d'") or
        run("lspci | grep -i nvidia") or
        "N/A"
    )

    specs["memory"] = run("free -h | awk '/Mem:/ {print $3 \"/\" $2}'")

    specs["packages"] = (
        run("pacman -Q | wc -l") or
        run("dpkg -l | wc -l") or
        "N/A"
    )

    specs["localip"] = run("hostname -I | awk '{print $1}'")

    return specs


# ---------------------------------------------------------------------------
#  FORMATTING RIGHT-SIDE TEXT
# ---------------------------------------------------------------------------

def make_info_block(specs, theme):
    bright = "\033[97m" if theme == "dark" else "\033[30m"
    dim = "\033[90m"
    reset = "\033[0m"

    lines = [
        f"{bright}OS{reset}:        {specs['os']}",
        f"{bright}Kernel{reset}:    {specs['kernel']}",
        f"{bright}Host{reset}:      {specs['host']}",
        f"{bright}Uptime{reset}:    {specs['uptime']}",
        f"{bright}Packages{reset}:  {specs['packages']}",
        f"{bright}Shell{reset}:     {specs['shell']}",
        f"{bright}DE{reset}:        {specs['de']}",
        f"{bright}WM{reset}:        {specs['wm']}",
        f"{bright}Terminal{reset}:  {specs['terminal']}",
        f"{bright}CPU{reset}:       {specs['cpu']}",
        f"{bright}GPU{reset}:       {specs['gpu']}",
        f"{bright}Memory{reset}:    {specs['memory']}",
        f"{bright}Local IP{reset}:  {specs['localip']}",
    ]

    return lines


# ---------------------------------------------------------------------------
#  MAIN ANIMATED DISPLAY
# ---------------------------------------------------------------------------

def animate(frames, specs_lines, fps=10):
    delay = 1 / fps
    width, _ = shutil.get_terminal_size()

    while True:
        for frame in frames:
            print("\033[H\033[2J", end="")  # clear

            for i in range(len(frame)):
                left = frame[i]
                right = specs_lines[i] if i < len(specs_lines) else ""
                print(left + "   " + right)

            time.sleep(delay)


# ---------------------------------------------------------------------------
#  PROGRAM ENTRY POINT
# ---------------------------------------------------------------------------

def main():
    default_frames = "~/.local/share/gifzitto/anim"

    import argparse
    p = argparse.ArgumentParser(description="gifzittofetch – animated system fetch tool")
    p.add_argument("--frames", default=default_frames, help="Folder containing ASCII frames")
    p.add_argument("--fps", type=int, default=12, help="Animation speed")
    args = p.parse_args()

    theme = detect_theme()
    specs = get_specs()

    frames = load_frames(args.frames)
    specs_block = make_info_block(specs, theme)

    animate(frames, specs_block, fps=args.fps)


if __name__ == "__main__":
    main()
